src/components/DeveloperMode.vue
PR for the first part of developer mode.
Contains:
- Private key to public key to address
- Address beautifier (remove or add '-' to address)
=> Developer mode - Account functions

src/components/DeveloperMode.vue, src/components/DeveloperModeAccount.vue, src/components/DeveloperModeConversion.vue
- Split DeveloperMode into smaller components
- Add String and number conversion tools
=> Developer Mode - Conversion Functions

src/components/Send.vue, src/components/wallet.vue
The following as been done in this PR: 
- Made menu options more visible 
- Removed divider in `Send.vue`
=> Simple UI Change

package-lock.json, package.json, src/components/Send.vue, src/components/SendConfirmation.vue, src/wallet.js
- Added send mosaic/asset functionality.  Transfer transactions now can send the network currency and custom assets as defined via a HEX ID. 
- NEM2-SDK also has been updated to the latest version.
- Added `SendConfirmation.vue` as a separate component 
In later PRs, I will refactor this to include functionality from the global state.
=> Sending Mosaic/Assets

src/components/namespace/Namespace.vue, src/components/namespace/NamespaceList.vue, src/components/namespace/NamespaceRegistration.vue
related #2 
- rent namespace and subnamespace
- list owned namespace
=> Namespace Component

src/components/developermode/DeveloperMode.vue, src/components/developermode/DeveloperModeAccount.vue, src/components/developermode/DeveloperModeTimestamp.vue
Final feature PR for developer mode
=> Developer Mode timestamp

src/components/namespace/Dialog.vue, src/components/namespace/Namespace.vue, src/components/namespace/NamespaceList.vue, src/components/namespace/NamespaceRegistration.vue, src/components/namespace/SendConfirmation.vue
related #2
- transaction send notification
- transaction status link
- show fullname and expiration
=> Namespace Component UI improvement

src/components/namespace/AliasTransaction.vue, src/components/namespace/Namespace.vue, src/components/namespace/NamespaceList.vue
#2
- address alias transaction
- mosaic alias transaction
- link and unlink
=> namespace alias address and mosaic

src/components/send/Send.vue, src/components/send/SendConfirmation.vue
I changed the UI on both to match the rest of the extension
=> ui changes on Send.vue and SendConfirmation.vue

src/components/asset/Asset.vue, src/components/asset/AssetCreation.vue, src/components/asset/AssetList.vue
#3 
Asset List
- mosaic id
- absolute balance
- relative balance
- expire info
- divisibility
- supply
- supply mutable
- transferable
=> Asset List

src/components/asset/AssetList.vue, src/components/wallet/Wallet.vue, src/components/wallet/WalletImport.vue
=> feat: import wallet from private key

package-lock.json, package.json, src/components/Errors.vue, src/components/Home.vue, src/components/WalletSelector.vue, src/components/asset/Asset.vue, src/components/asset/AssetList.vue, src/components/asset/AssetTab.vue, src/components/namespace/Namespace.vue, src/components/namespace/NamespaceList.vue, src/components/utils/getAccountInfo.js, src/components/utils/getMosaicsByAddress.js, src/components/wallet/Wallet.vue, src/components/wallet/WalletCreation.vue, src/components/wallet/WalletImport.vue, src/components/wallet/WalletList.vue, src/infrastructure/StateRepository.js, src/wallet.scss
Error management at the root component level
on wallet change, account info and get mosaics are called.
asset list, with owned assets
homepage
all errors fixed and signed build tested
misc cosmetics
=> global error management, assets and home

src/components/App.vue, src/components/Errors.vue, src/components/Home.vue, src/components/asset/Asset.vue, src/components/developermode/DeveloperMode.vue, src/components/namespace/Namespace.vue, src/components/send/Send.vue, src/components/wallet/Wallet.vue, src/wallet.scss
- enable drawer toggle
- use flex shrink and grow for app main flex props
- make view titles uniform
- use standard v-alert for errors
I wanted to split this PR, but I messed up with git rebase... :s
Could we agree on the prettier we use so we avoid some commit noise?
=> enable menu toggle, use flex grow and shrink

src/components/Home.vue, src/components/transactions/Transactions.vue, src/components/utils/formatTransaction.js, src/components/utils/getAccountTransactionsById.js, src/infrastructure/StateRepository.js
Now there is no method to get more than 50 lines, but will do it next (that's why I called the method `getAccountTransactions**ById**`)
I didn't really tweak the table design, nor its sorting method
I plugged an issue on the fee field of the transaction object, I'll investigate it later
About your concerns related to the utils folder, I'm thinking that it might be better to put the JS files in the components folder, so here, the 2 new ones could go to components/transactions.
=> Transactions

src/components/Confirmation.vue
Receives a transaction
Display the dialog to the user
If OK, send. If not OK, do nothing.
Use the slot to display any value
=> Confirmation Component

src/components/App.vue, src/components/Home.vue, src/components/WalletSelector.vue, src/components/transactions/Transactions.vue, src/components/utils/formatTransaction.js, src/components/utils/getAccountInfo.js, src/components/utils/getAccountTransactionsById.js, src/components/wallet/WalletList.vue, src/infrastructure/StateRepository.js
- Wallet data reload is triggered when this.activeWallet is modified
- Wallet selector takes this value from props for being reactive to all events (including deleting an active wallet and setting an active wallet at wallet creation)
- Fix broken error resource not found
- Show active wallet info in homepage even if the wallet is errored
=> Boost wallet UX

src/components/Confirmation.vue
If put LockFundsTx to this component from another component, its hash should be dummy.
If transaction type is LOCK, its hash is the hash of next signed transaction in the array.
Transaction Announce Sequentially
first, announce transaction[0]
after transactions[0] is confirmed, then announce transactions[1]
after transactions[1] is confirmed, then announce transactions[2]...
=> ComfirmationComponent receive transaction array props

src/components/transactions/TransactionModal.vue, src/components/utils/formatTransactions.js, src/components/utils/getAccountTransactionsById.js, src/infrastructure/StateRepository.js
add specific transaction fields on the modal
I let the account modification ones as @TODO
=> Tx modal types

src/components/namespace/AliasTransaction.vue, src/components/namespace/NamespaceRegistration.vue
compatible for confirmation component
- register namespace transaction
- alias transaction
=> comfirmation component used by namespace tx

package-lock.json, src/components/asset/AssetCreation.vue, src/components/asset/AssetList.vue, src/components/asset/AssetModification.vue, src/components/asset/AssetTab.vue, src/components/utils/formatMosaics.js, src/components/utils/formatTransactions.js, src/wallet.scss
- modify an asset supply
- support of unlimited duration mosaics _(have to watch out for the [SDK update as accountHttp.transactions does not support this feature](https://github.com/nemtech/nem2-sdk-typescript-javascript/pull/120), so I assumed that the duration value will be 0 and not undefined)_
- minor enhancements of the create asset form
- put back the package-lock that I deleted yesterday to pass the merge conflict
=> Asset supply

src/components/App.vue, src/components/asset/AssetModification.vue, src/components/filter/AddFilter.vue, src/components/filter/Filter.vue, src/components/filter/FilterTransaction.vue, src/components/filter/SendConfirmation.vue, src/wallet.js
I added a panel to modify filter.
On the one hand, the PropertyType is divided into two parts, allow and block. On the other hand ,it is also divided into parts address, mosaic, transaction.
The new code Implement three kind of filters.
=> add transaction filter

src/components/AddressInput.vue, src/components/transactions/TransactionModal.vue, src/components/transactions/Transactions.vue, src/components/transactions/transactionListFilters.vue, src/store/application.js, src/store/transactions.js
rationalize modal handling
this seems to be the best way for handling dialog components that are separate from their parents
=> Modal mutation

src/components/App.vue, src/components/transactions/Transactions.vue, src/infrastructure/transactions/formatTransactions.js, src/store/application.js, src/store/transactions.js, src/store/wallet.js
=> Transaction listeners

src/components/transactions/Transactions.vue, src/infrastructure/transactions/getAccountTransactionsById.js, src/store/transactions.js, src/store/wallet.js
- Handle error when accountHttp.transactions fails
- Fix minor error when a wallet was deleted
=> Error management

src/components/WalletSelector.vue, src/components/wallet/WalletCreationDialog.vue, src/components/wallet/WalletImportDialog.vue
=> Wallets: minor design enhancement

package-lock.json, package.json, src/components/Confirmation.vue, src/components/uriHandler/Handler.vue, src/components/uriHandler/UriTransactionList.vue
**Feature abstract**:
When wallet is called via [nem2-uri-schema](https://github.com/dgarcia360/nem2-uri-scheme) and the URI has the webhook defined, then the wallet performs a POST request to the webhook URL with the parameters:
```json
{
"action": "AnnounceTransaction",
"data": {
"hash":  "string",
"signer":"string"
}
}
```
=> adding webhook

src/components/multisig/Multisig.vue, src/components/multisig/MultisigModification.vue, src/components/multisig/OtherMultisigTransactions.vue, src/components/multisig/otherMultisigTransactionComponents/Transfer.vue, src/store/wallet.js
1. modified the view in multisig transfer transaction ;
2.Implemented the transfer multisig complete transaction in multisig panel
=> Implemented transfer multisig complete transaction 

src/components/send/Send.vue
=> fix generationhash bug and add form validations

src/components/asset/AssetCreation.vue, src/components/asset/AssetModification.vue, src/components/filter/AddFilter.vue, src/components/filter/FilterTransaction.vue, src/components/filter/SendConfirmation.vue, src/components/multisig/MultisigModification.vue, src/components/multisig/otherMultisigTransactionComponents/Transfer.vue, src/components/send/Send.vue, src/components/transactions/tabs/Transfer.vue, src/infrastructure/transactions/errorMessage.js, src/infrastructure/transactions/getAccountTransactionsById.js
fix filter and add form validations in it
update  form validations in transfer
=> fix filter and update  form validations

src/components/SendConfirmation.vue, src/components/asset/AssetAlias.vue, src/components/asset/AssetModification.vue, src/components/asset/AssetTab.vue, src/components/namespace/AliasTransaction.vue, src/infrastructure/transactions/formatTransactions.js
along with misc minor fixes
I'll display if an asset has an alias or not in another PR
=> add alias to asset

src/components/multisig/Confirmation.vue, src/components/multisig/MultisigConversion.vue, src/components/multisig/MultisigCosignation.vue, src/components/multisig/MultisigModification.vue, src/components/multisig/otherMultisigTransactionComponents/Transfer.vue
1. An account can get aggrefate transactions search by sender's public key ;
2. update ModifyMultisig.
=>  update cosign aggregate transactions
